version: '3'

services:
  db1:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=watcher
      - POSTGRES_PASSWORD=******** # change it to your own
      - POSTGRES_DB=watcher
    volumes:
      - ../postgres-watcher:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    restart: always
    environment:
      - POSTGRES_PASSWORD=******** # change it to your own (the same as above)
      - DJANGO_EMAIL_HOST=127.0.0.1 # your mail server's setting
      - DJANGO_EMAIL_PORT=25 # your mail server's settins
      - DJANGO_EMAIL_HOST_USER=  # your mail server's auth data
      - DJANGO_EMAIL_HOST_PASSWORD=  # your mail server's auth data
      - DJANGO_EMAIL_FROM=  # email address to send alerts from
    build: .
    volumes:
      - .:/var/www/watcher
    ports:
      - 8090:8090
    depends_on:
      - db1