# Generated by Django 3.1 on 2021-08-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrix',
            name='metrix_active',
        ),
        migrations.AddField(
            model_name='metrix',
            name='metrix_token',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
