# Generated by Django 3.1 on 2021-08-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0006_auto_20210829_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrix',
            name='metrix_netconn',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrix',
            name='metrix_netif',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrix',
            name='metrix_swap',
            field=models.CharField(default=None, max_length=25400),
        ),
    ]
