# Generated by Django 3.1 on 2021-08-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0007_auto_20210829_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrix',
            name='metrix_netconn',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='metrix',
            name='metrix_netif',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='metrix',
            name='metrix_proc',
            field=models.TextField(blank=True, default=None),
        ),
    ]
