# Generated by Django 3.1 on 2021-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0008_auto_20210829_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrix',
            name='metrix_ram',
            field=models.JSONField(),
        ),
    ]
