# Generated by Django 3.1 on 2021-09-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0009_auto_20210903_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrix',
            name='metrix_ram',
            field=models.JSONField(default=None),
        ),
    ]
