# Generated by Django 3.1 on 2021-09-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0010_auto_20210903_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrix',
            name='metrix_swap',
            field=models.JSONField(default=None),
        ),
    ]
