# Generated by Django 3.1 on 2021-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0012_auto_20210903_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrix',
            name='metrix_users',
            field=models.JSONField(default=None),
        ),
    ]
