# Generated by Django 3.1 on 2021-10-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0014_auto_20211031_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrix',
            name='metrix_netconn',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='metrix',
            name='metrix_netif',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='metrix',
            name='metrix_rom',
            field=models.JSONField(default=None),
        ),
    ]
