# Generated by Django 3.1 on 2021-11-20 12:07

from django.db import migrations, models
import watcherapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0015_auto_20211031_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='active_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='active',
            name='active_token',
            field=models.CharField(default=watcherapp.models.token_gen, max_length=256),
        ),
    ]
