# Generated by Django 3.1 on 2022-11-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0018_auto_20221121_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='active_cpu_limit',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='active',
            name='active_ram_limit',
            field=models.IntegerField(blank=True, default=100),
        ),
        migrations.AlterField(
            model_name='active',
            name='active_rom_limit',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
