# Generated by Django 3.1 on 2022-11-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcherapp', '0019_auto_20221123_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
